Move device parser utility function
PyTorchLightning/pytorch-lightning pull request #10230
Opened 2021-10-28 20:55 UTC by awaelchli

## What does this PR do?

Addresses comment https://github.com/PyTorchLightning/pytorch-lightning/pull/9987#discussion_r738686821

The Trainer and Lite share a device parsing logic. We can move this static method out of Trainer and place it where the rest of the device parsing lives. This way, Lite does not need to import the Lightning Trainer.

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)
   Changelog not needed, the function was protected/internal

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
I made sure I had fun coding 🙃

Part of #1 (it's a lie, this is just here to avoid noisy GitHub bot)

2021-10-30 11:52 UTC, awaelchli commented on pytorch_lightning/trainer/trainer.py
> -        gpu_ids = device_parser.parse_gpu_ids(gpus)
resolved

2021-10-30 12:07 UTC, awaelchli commented on pytorch_lightning/utilities/device_parser.py
> +) -> Tuple[Optional[List[int]], Optional[Union[List[int], int]]]:
Sounds good! How do you like  #10265 ?

2021-10-30 14:55 UTC, carmocca approved these changes

2021-11-04 03:52 UTC, kaushikb11 requested changes
@awaelchli I had discussed to keep the Trainer method, and use the utility function inside it

2021-11-04 09:39 UTC, awaelchli commented
Changed

2021-11-04 10:17 UTC, justusschock approved these changes

2021-11-04 12:41 UTC, kaushikb11 approved these changes

2021-11-05 10:18 UTC, tchaton approved these changes
LGTM !

2021-11-05 10:18 UTC, merged