Remove deprecated datamodule lifecycle properties
PyTorchLightning/pytorch-lightning pull request #10350
Opened 2021-11-04 13:00 UTC by mayeroa

## What does this PR do?

Fixes #10312

### Does your PR introduce any breaking changes? If yes, please list them.

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2021-11-04 15:22 UTC, awaelchli approved these changes

2021-11-04 15:46 UTC, ananthsub requested changes
Thanks for working on this @mayeroa !
With this change, we should also remove the following:
- https://github.com/PyTorchLightning/pytorch-lightning/blob/ce3e63262a7247c1111375b28c90bdd83b42bf3f/pytorch_lightning/core/datamodule.py#L94-L105
- https://github.com/PyTorchLightning/pytorch-lightning/blob/ce3e63262a7247c1111375b28c90bdd83b42bf3f/pytorch_lightning/core/datamodule.py#L409-L483
- Any references to these properties in the trainer, like here: https://github.com/PyTorchLightning/pytorch-lightning/blob/ce3e63262a7247c1111375b28c90bdd83b42bf3f/pytorch_lightning/trainer/connectors/data_connector.py#L143

2021-11-04 15:46 UTC, ananthsub commented on tests/core/test_datamodules.py
> +    assert not dm._has_prepared_data
we should be able to remove this whole test now

2021-11-04 15:46 UTC, ananthsub commented on tests/core/test_datamodules.py
> +    assert not dm._has_setup_fit
same for this test

2021-11-04 21:50 UTC, mayeroa commented
Should be better now :)

2021-11-04 22:42 UTC, ananthsub commented on docs/source/extensions/datamodules.rst
> +    any duplicate ``dm.setup('fit')`` calls will be a no-op.
This note must be removed now as well as this removal changes this behavior

```
note::
    ``{setup,teardown,prepare_data}`` call will be only called once for a specific stage.
    If the stage was ``None`` then we assume ``{fit,validate,test}`` have been called. For example, this means that
    any duplicate ``dm.setup('fit')`` calls will be a no-op. 
```

2021-11-05 03:29 UTC, carmocca approved these changes
Big one!

2021-11-05 03:44 UTC, ananthsub approved these changes

2021-11-05 05:03 UTC, merged