fix path separator in neptune logger
PyTorchLightning/pytorch-lightning pull request #10500
Opened 2021-11-12 10:26 UTC by monty5811

## What does this PR do?

The neptune logger fails on windows as the expected path in `_get_full_model_name` assumes that the separator is `/`.
This PR uses `os.sep` instead.

Fixes: n/a

### Does your PR introduce any breaking changes? If yes, please list them.

None

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2021-11-19 03:04 UTC, awaelchli approved these changes

2021-11-19 03:09 UTC, carmocca approved these changes

2021-11-19 03:17 UTC, akihironitta approved these changes

2021-11-19 03:30 UTC, akihironitta requested changes
Seems like the tests failed on Windows.

```
FAILED tests/loggers/test_neptune.py::TestNeptuneLogger::test_after_save_checkpoint
FAILED tests/loggers/test_neptune.py::TestNeptuneLoggerUtils::test__get_full_model_name
```

2021-11-19 12:03 UTC, Raalsky commented
> Seems like the tests failed on Windows.
> 
> ```
> FAILED tests/loggers/test_neptune.py::TestNeptuneLogger::test_after_save_checkpoint
> FAILED tests/loggers/test_neptune.py::TestNeptuneLoggerUtils::test__get_full_model_name
> ```

It seems there are strict Posix paths in mocks/assertions :wink:. You should update them accordingly with `os.path.join` etc.

2021-11-25 21:04 UTC, Raalsky commented
I think it could be closed as we already took a care of separator and tests in https://github.com/PyTorchLightning/pytorch-lightning/pull/10369 .

2021-12-17 17:07 UTC, awaelchli commented
Closing as it was already included in the linked PR. Thanks @monty5811 for taking a stab at this.

2021-12-17 17:07 UTC, closed without merging