Fix frozen dataclass instance error in apply_to_collection function
PyTorchLightning/pytorch-lightning pull request #10927
Opened 2021-12-03 17:26 UTC by abhi-rf

## What does this PR do?

changed the set_attribute function in in the apply_to_collection for recursively applying a function to all elements of a certain dtype in utilities/apply_func.py

Fixes #10873 

### Does your PR introduce any breaking changes? If yes, please list them.

<None>

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun? Yes

Make sure you had fun coding 🙃

2021-12-03 18:59 UTC, justusschock requested changes
Sorry, but I feel I need to block this for now. I think this violates the core idea of a python frozen dataclass (which is being immutable) and therefore it should not be hacked around this. Let's discuss in #10873 .

If I'm outvoted I will happily open this PR again. Just want to prevent merging until a common decision was made

2021-12-03 18:59 UTC, justusschock commented on pytorch_lightning/utilities/apply_func.py
> +            object.__setattr__(result, field_name, v)
I don't think we should use this all the time. Only fall back to this if necessary and use `setattr(result, field_name, v)` the remaining time.

2021-12-04 11:15 UTC, abhi-rf commented
> Sorry, but I feel I need to block this for now. I think this violates the core idea of a python frozen dataclass (which is being immutable) and therefore it should not be hacked around this. Let's discuss in #10873 .
> 
> If I'm outvoted I will happily open this PR again. Just want to prevent merging until a common decision was made

Sure, makes sense. I did not think of it as a way to prevent python from doing its job. In that case, it is prefectly fine to close the PR.

2021-12-10 09:57 UTC, abhi-rf reviewed
Raised error instead of forcing the apply

2021-12-10 14:13 UTC, justusschock reviewed
@abhi-rf Would you mind to also add a test case for this?

2021-12-10 17:14 UTC, abhi-rf commented
> @abhi-rf Would you mind to also add a test case for this?

Sure, I have not done this before but can surely give it a try!!

2021-12-13 12:07 UTC, carmocca commented
@abhi-rf You can find its existing tests in `tests/utilities/test_apply_func.py`

2021-12-21 08:55 UTC, tchaton approved these changes
LGTM !

2021-12-21 08:55 UTC, tchaton commented on pytorch_lightning/utilities/apply_func.py
> +            except dataclasses.FrozenInstanceError:
Neat! Let's add an associated test there.

2022-01-05 21:07 UTC, carmocca commented on pytorch_lightning/utilities/apply_func.py
> +            except dataclasses.FrozenInstanceError:
Done

2022-01-05 21:10 UTC, carmocca approved these changes

2022-01-05 22:29 UTC, awaelchli approved these changes

2022-01-05 22:29 UTC, merged