Depricate on_before_accelerator_backend_setup
PyTorchLightning/pytorch-lightning pull request #11568
Opened 2022-01-21 21:30 UTC by krishnakalyan3

## What does this PR do?

Fixes #\<issue_number>

### Does your PR introduce any breaking changes? If yes, please list them.

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [ ] Is this pull request ready for review? (if not, please submit in draft mode)
- [ ] Check that all items from **Before submitting** are resolved
- [ ] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2022-01-21 21:31 UTC, krishnakalyan3 commented
Fixes #11559

2022-01-21 22:09 UTC, ananthsub requested changes
Thanks for working on this @krishnakalyan3 

I'd make this into 2 PRs:
1. Transition all Lightning callbacks to use `setup` instead of `on_before_accelerator_backend_setup`. These callsites are shared in the initial issue
2. Mark the callback hook as deprecated (adding to the config validator, change the docstring of the hook to reflect it's deprecated, etc)

2022-01-21 22:09 UTC, ananthsub commented on docs/source/extensions/callbacks.rst
> -
Don't remove this from the docs. Instead add to the docstring that this hook is deprecated, and it'll render on the docs site

2022-01-21 22:09 UTC, ananthsub commented on pytorch_lightning/trainer/callback_hook.py
> +    def setup(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule", stage: Optional[str] = None) -> None:
this should not be changed. this was the old convention for how callback hooks were called

2022-01-21 22:32 UTC, krishnakalyan3 commented
@ananthsub These are the callbacks referenced by `on_before_accelerator_backend_setup`. Their functions signature already looks correct according to me. I felt that those changes were minimal. Can you please let me know if I missed out on something? If yes I would be happy to create another PR for it.

```
./pytorch_lightning/callbacks/pruning.py:    def on_before_accelerator_backend_setup(self, trainer: "pl.Trainer", pl_module: LightningModule) -> None:
./pytorch_lightning/callbacks/finetuning.py:    def on_before_accelerator_backend_setup(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule"):
./pytorch_lightning/callbacks/stochastic_weight_avg.py:    def on_before_accelerator_backend_setup(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule"):
./pytorch_lightning/callbacks/lambda_function.py:        on_before_accelerator_backend_setup: Optional[Callable] = None,
./pytorch_lightning/callbacks/base.py:    def on_before_accelerator_backend_setup(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:```

2022-01-22 01:59 UTC, ananthsub reviewed
This needs to be updated too: https://github.com/PyTorchLightning/pytorch-lightning/blob/76c23f34b889fdce3351d1b1c2f657d52ff95bb2/tests/callbacks/test_stochastic_weight_avg.py#L236-L241

2022-01-22 01:59 UTC, ananthsub commented on tests/callbacks/test_finetuning_callback.py
> +        def setup(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
```suggestion
        def setup(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule", stage: Optional[str] = None) -> None:
```

2022-01-22 16:11 UTC, krishnakalyan3 commented
Since this is a minor change do I need to update the change logs?.

2022-01-22 17:34 UTC, daniellepintz commented
A few comments:
1. It looks like you are missing references in two tests: `test_swa_deepcopy` and `test_deepspeed_assert_config_zero_offload_disabled`
2.  no need to update the changelog for this, but in the next PR yes
3. please update the title and description of this PR. this PR no longer fixes the issue directly, that will be the next PR

2022-01-23 16:43 UTC, krishnakalyan3 commented
@daniellepintz Let me know if the new changes look good?.

2022-01-23 18:07 UTC, daniellepintz commented on tests/callbacks/test_stochastic_weight_avg.py
> +            super().__init__(*args, **kwargs)
```suggestion
            super().setup(trainer, pl_module, stage)
```

2022-01-23 18:10 UTC, daniellepintz commented
@krishnakalyan3 Looks good! Two things:
1. I see a few references of `on_before_accelerator_backend_setup_called` across the tests, this should be updated to `setup_called`
2. Please update the title to "Replace occurrences of `on_before_accelerator_backend_setup_called` with `setup` hook"

2022-01-23 20:07 UTC, krishnakalyan3 commented
@daniellepintz let me know if this looks better.

2022-01-23 20:22 UTC, daniellepintz approved these changes
LTGM! Please fix the lint errors. You can check lint locally by running `pre-commit` (https://pre-commit.com/)

2022-01-23 20:38 UTC, awaelchli approved these changes

2022-01-23 20:38 UTC, awaelchli commented on tests/callbacks/test_finetuning_callback.py
> +        def setup(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule", stage: Optional[str] = None) -> None:
that looks fine to me, just fyi we usually don't add typing to the tests as it adds very little value

2022-01-23 22:43 UTC, krishnakalyan3 commented
@awaelchli let me know if the new changes look okay?.

2022-01-23 23:08 UTC, krishnakalyan3 commented
@daniellepintz 

Looks like the pre-commit messages are picking up this 
```
tests/strategies/test_deepspeed_strategy.py:409: [F821] undefined name 'pl'
tests/strategies/test_deepspeed_strategy.py:409: [F821] undefined name 'pl'
tests/callbacks/test_finetuning_callback.py:271: [F821] undefined name 'pl'
tests/callbacks/test_finetuning_callback.py:271: [F821] undefined name 'pl'
tests/callbacks/test_stochastic_weight_avg.py:236: [F821] undefined name 'pl'
tests/callbacks/test_stochastic_weight_avg.py:236: [F821] undefined name 'pl'
```

2022-01-23 23:13 UTC, awaelchli commented
add `import pytorch_lightning as pl `
:)

2022-01-24 09:29 UTC, rohitgr7 commented on tests/callbacks/test_stochastic_weight_avg.py
> +import pytorch_lightning as pl
```suggestion
```

2022-01-24 09:29 UTC, rohitgr7 commented on tests/callbacks/test_stochastic_weight_avg.py
> +        def setup(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
```suggestion
        def setup(self, trainer, pl_module, stage=None) -> None:
```

2022-01-24 09:29 UTC, rohitgr7 commented on tests/strategies/test_deepspeed_strategy.py
> +import pytorch_lightning as pl
```suggestion
```

2022-01-24 09:29 UTC, rohitgr7 commented on tests/strategies/test_deepspeed_strategy.py
> +        def setup(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
```suggestion
        def setup(self, trainer, pl_module, stage=None) -> None:
```

2022-01-24 09:29 UTC, rohitgr7 commented on tests/callbacks/test_finetuning_callback.py
> +import pytorch_lightning as pl
```suggestion
```

2022-01-24 09:29 UTC, rohitgr7 commented on tests/callbacks/test_finetuning_callback.py
> +        def setup(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
```suggestion
        def setup(self, trainer, pl_module, stage=None) -> None:
```

2022-01-24 09:29 UTC, rohitgr7 commented on tests/callbacks/test_stochastic_weight_avg.py
> +            super().setup(trainer, pl_module)
```suggestion
            super().setup(trainer, pl_module, stage)
```

2022-01-24 09:29 UTC, rohitgr7 commented on tests/callbacks/test_stochastic_weight_avg.py
> +        def setup(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
setup needs a stage parameter right?

2022-01-24 09:29 UTC, rohitgr7 commented on tests/callbacks/test_stochastic_weight_avg.py
> +import pytorch_lightning as pl
typing isn't required.

2022-01-24 10:57 UTC, krishnakalyan3 commented
@rohitgr7 since `stage` is not referenced anywhere don't we have to initialize it somewhere as a global or a local variable?.

2022-01-24 11:24 UTC, rohitgr7 commented
> 

@krishnakalyan3 `stage` will be set up trainer and passed to the callback's `setup` internally.
for tests, typing isn't required.

2022-01-25 12:51 UTC, rohitgr7 approved these changes

2022-01-25 17:48 UTC, ananthsub approved these changes

2022-01-25 17:56 UTC, carmocca approved these changes

2022-02-03 04:14 UTC, merged