Deprecate `on_before_accelerator_backend_setup` callback hook
PyTorchLightning/pytorch-lightning pull request #11655
Opened 2022-01-28 18:11 UTC by krishnakalyan3

## What does this PR do?

Fixes #11559

### Does your PR introduce any breaking changes? If yes, please list them.

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2022-01-28 18:20 UTC, krishnakalyan3 commented
@ananthsub this is part 2 of [this](https://github.com/PyTorchLightning/pytorch-lightning/pull/11568) PR. Does it look okay?

2022-01-28 19:26 UTC, daniellepintz commented
@krishnakalyan3 currently this PR is only changing the changelog. It should be deprecating the hook, like in https://github.com/PyTorchLightning/pytorch-lightning/pull/10940

Please also update the title to be the same as #11559

2022-01-28 19:31 UTC, daniellepintz commented on CHANGELOG.md
> +- Deprecated `on_before_accelerator_backend_setup`callback ([#11568](https://github.com/PyTorchLightning/pytorch-lightning/pull/11568))
This section is for what was deprecated in v1.5. Please move this line up to ~282

2022-01-28 20:20 UTC, ananthsub requested changes
Requesting changes based on @daniellepintz 's feedback

2022-01-31 08:51 UTC, tchaton approved these changes
LGTM once comments are addressed.

2022-01-31 15:19 UTC, daniellepintz commented
The title and description of this PR don't match the contents - you seem to be removing the `on_pretrain_routine_start` hooks

2022-02-02 08:47 UTC, krishnakalyan3 commented
@daniellepintz You are right. Now, this PR only contains the change log.

2022-02-02 08:48 UTC, krishnakalyan3 commented
Part 2/2 #11550

2022-02-07 09:09 UTC, ananthsub commented on pytorch_lightning/trainer/configuration_validator.py
> +def _check_on_before_accelerator_backend_setup(trainer: "pl.Trainer", model: "pl.LightningModule") -> None:
`model` isn't used - remove it from the function signature

2022-02-07 09:09 UTC, ananthsub commented on tests/deprecated_api/test_remove_1-8.py
> +        trainer.validate(model)
you only need to call one of these functions for the test

2022-02-07 09:41 UTC, ananthsub approved these changes

2022-02-07 10:02 UTC, rohitgr7 approved these changes

2022-02-07 10:49 UTC, krishnakalyan3 commented
Thanks @rohitgr7

2022-02-07 11:07 UTC, merged

2022-02-07 15:36 UTC, carmocca commented on tests/callbacks/test_finetuning_callback.py
>  def test_on_before_accelerator_backend_setup(tmpdir):
Probably not, it's also covered by `tests/models/test_hooks.py::test_trainer_model_hook_system_fit`