Rename `base.py` to `loop.py`
PyTorchLightning/pytorch-lightning pull request #11982
Opened 2022-02-18 07:02 UTC by valanm22

## What does this PR do?

Fixes #11974

### Does your PR introduce any breaking changes? If yes, please list them.

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2022-02-18 07:36 UTC, ananthsub requested changes
Thanks for working on this @valanm22 ! You'll also need to update all of the import paths wherever `pytorch_lightning.loops.base.py` is referenced:
https://github.com/PyTorchLightning/pytorch-lightning/search?q=loops.base

2022-02-22 04:54 UTC, akihironitta commented on docs/source/extensions/loops_advanced.rst
> +The two hooks :meth:`~pytorch_lightning.loops.loop.Loop.on_save_checkpoint` and :meth:`~pytorch_lightning.loops.base.Loop.on_load_checkpoint` function very similarly to how LightningModules and Callb
```suggestion
The two hooks :meth:`~pytorch_lightning.loops.loop.Loop.on_save_checkpoint` and :meth:`~pytorch_lightning.loops.loop.Loop.on_load_checkpoint` function very similarly to how LightningModules and Callbacks save and load state.
```

2022-02-28 10:02 UTC, tchaton commented on pytorch_lightning/loops/epoch/prediction_epoch_loop.py
> +from pytorch_lightning.loops.loop import Loop
Let's add a 1 cycle depreceation. Some projects are relying on the `from pytorch_lightning.loops.base import Loop`

2022-03-21 19:53 UTC, daniellepintz commented
Hi @valanm22 are you planning on finishing this PR?

2022-03-21 20:01 UTC, valanm22 commented
yes, but can I get some instructions on this?

2022-03-21 22:08 UTC, daniellepintz commented
sure, could you clarify what exactly you are blocked on?

2022-03-22 03:04 UTC, valanm22 commented
How to find out the other files that need to be changed?

2022-03-22 03:31 UTC, akihironitta commented
Hi @valanm22! Thank you for working on this!

> How to find out the other files that need to be changed?

If you're familiar with a cli tool called `grep`, you can run the following command:
```console
$ grep -rnI "base.loop" .
```

There are also useful tools like the followings:
- https://grep.app/search?q=loops.base&filter[repo][0]=PyTorchLightning/pytorch-lightning
- https://cs.github.com/?scopeName=All+repos&scope=&q=repo%3APyTorchLightning%2Fpytorch-lightning+%22loops.base%22

2022-05-12 16:05 UTC, carmocca commented
Closing this one, since you gave the greenlight to another contributor to continue. Thanks for your time!

2022-05-12 16:05 UTC, closed without merging