Rearrange Logger Documentation
PyTorchLightning/pytorch-lightning pull request #12333
Opened 2022-03-15 07:06 UTC by manangoel99

## What does this PR do?

This PR rearranges the logger documentation and adds usage of jupyter magic command for wandb

### Does your PR introduce any breaking changes? If yes, please list them.

## Before submitting

- [ ] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [x] Did you make sure to **update the documentation** with your changes? (if necessary)
- [x] Did you write any **new necessary tests**? (not for typos and docs)
- [x] Did you verify new and **existing tests pass** locally with your changes?
- [x] Did you list all the **breaking changes** introduced by this pull request?
- [x] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2022-03-15 07:31 UTC, ananthsub commented on CHANGELOG.md
> +- `%%wandb` magic command to the WandbLogger usage
1. docs changes typically don't require changelog entries
2. this is the oldest section in the changelog - newer updates should be added at the top

2022-03-15 07:32 UTC, ananthsub commented on docs/source/api_references.rst
> +    wandb
this list is alphabetized. why is `wandb` being moved up?

2022-03-15 07:32 UTC, ananthsub commented on docs/source/common/loggers.rst
> +Weights and Biases
same question here

2022-03-15 07:42 UTC, manangoel99 commented
I've made the suggested changes and pulled the commits from master to this branch to get it up-to-date

2022-03-15 08:21 UTC, krshrimali requested changes
Hi, @manangoel99 - Thanks for the PR! Left a minor comment, but also curious: from the description of this PR: `This PR rearranges the logger documentation and adds usage of jupyter magic command for wandb`.

Can you please point me to the change (line of code) which adds usage of jupyter magic command for wandb in this PR?

I'm also concerned about re-arranging, unless and until it was discussed in an issue before or has a reason that everyone agrees with (if it was discussed before, please feel free to point me to the discussion :)). cc: @kaushikb11 @awaelchli @Borda

2022-03-15 08:21 UTC, krshrimali commented on docs/source/extensions/logging.rst
> +    WandbLogger
As @ananthsub mentioned, can you please keep the list alphabetized?

2022-03-15 08:21 UTC, krshrimali commented on docs/source/extensions/logging.rst
>      TensorBoardLogger
```suggestion
    CometLogger
    CSVLogger
    MLFlowLogger
    NeptuneLogger
    TensorBoardLogger
    WandbLogger
```

2022-03-15 08:34 UTC, rohitgr7 commented on docs/source/common/loggers.rst
> +    %%wandb
as @krshrimali mentioned, the addition of this part is fine. Other seems unimportant. You can extend this one too if there's anything more to add here.

2022-03-16 10:06 UTC, manangoel99 commented
I've put everything back in the alphabetical order and added usage of the `%%wandb` magic command.

2022-03-16 11:47 UTC, rohitgr7 commented on docs/source/common/loggers.rst
> +To visualize using wandb in a jupyter notebook environment use the following magic line command
```suggestion
To visualize using wandb in a jupyter notebook environment use the following magic line command:
```

2022-03-16 11:47 UTC, rohitgr7 commented on docs/source/common/loggers.rst
> +    %%wandb
does it take any arguments here?

2022-03-16 11:47 UTC, rohitgr7 commented on docs/source/common/loggers.rst
> +To visualize using wandb in a jupyter notebook environment use the following magic line command
can you extend this example?
visualize after training or during training?

or maybe link this too: https://docs.wandb.ai/guides/track/jupyter#additional-jupyter-features-in-w-and-b

2022-03-16 12:57 UTC, krshrimali commented
Thanks, @manangoel99 for updating this PR. Appreciate the contribution. Just FYI (apart from @rohitgr7's comments) - I updated the description and title of this PR, feel free to make further edits if any changes required. :)

2022-03-16 13:56 UTC, rohitgr7 approved these changes

2022-03-16 13:56 UTC, rohitgr7 commented on docs/source/common/loggers.rst
> +More information is available `here https://docs.wandb.ai/guides/track/jupyter` __.
```suggestion
More information is available `here https://docs.wandb.ai/guides/track/jupyter`__.
```

2022-03-17 02:46 UTC, akihironitta reviewed
@manangoel99 Could we document a magic command for tensorboard as well in this PR?

2022-03-17 11:47 UTC, krshrimali commented
> @manangoel99 Could we document a magic command for tensorboard as well in this PR?

That would be a good addition, thanks @akihironitta for suggesting this. @manangoel99 - if you feel comfortable doing it in this PR, that would be great, but if you want to do it in another PR, that's totally fine as well. Just let us know :)

2022-03-17 12:01 UTC, rohitgr7 commented
lets add it here

2022-03-17 13:11 UTC, manangoel99 commented
@krshrimali @rohitgr7 Thanks for adding this to the PR. I actually found the Tensorboard instructions elsewhere so I skipped those initially.
https://pytorch-lightning.readthedocs.io/en/latest/extensions/logging.html

2022-03-17 13:54 UTC, rohitgr7 commented
yep! I noticed. But we will probably remove tensorboard as default in the future so the existing one will be updated then.

2022-03-19 19:25 UTC, awaelchli approved these changes

2022-03-19 19:25 UTC, awaelchli commented on docs/source/common/loggers.rst
> +To see your logs in terminal, run the following command:
but you won't see the logs in the terminal :( 

```suggestion
To see your logs, run the following command in the terminal:
```

2022-03-19 19:25 UTC, awaelchli commented on docs/source/common/loggers.rst
> +To visualize using wandb in a jupyter notebook environment use the following magic line command:
this is all nice and useful, but we need to be careful not to replicate wandb documentation into our own docs. just as a note for the future.

2022-03-21 04:34 UTC, krshrimali approved these changes
LGTM, thanks @manangoel99 for your contribution.

2022-03-28 17:09 UTC, carmocca commented
@manangoel99 There are some docs failures:

`/home/runner/work/pytorch-lightning/pytorch-lightning/docs/source/common/loggers.rst:: ERROR: Anonymous hyperlink mismatch: 1 references but 0 targets.`

cc @rohitgr7 (if you know what's the cause)

2022-03-28 17:53 UTC, rohitgr7 commented on docs/source/common/loggers.rst
> +More information is available `here https://docs.wandb.ai/guides/track/jupyter`__.
```suggestion
More information is available `here <https://docs.wandb.ai/guides/track/jupyter>`__.
```

2022-03-29 02:09 UTC, kaushikb11 approved these changes

2022-03-29 04:15 UTC, merged