Add typing to `LightningModule.trainer`
PyTorchLightning/pytorch-lightning pull request #12345
Opened 2022-03-16 15:42 UTC by jlhbaseball15

## What does this PR do?

This is a small change that adds typing to the trainer object within the LightningModule.

Fixes #12337 

### Does your PR introduce any breaking changes? If yes, please list them.

## Before submitting

- [x] Was this **discussed/approved** via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your **PR does only one thing**, instead of bundling different changes together?
- [ ] Did you make sure to **update the documentation** with your changes? (if necessary)
- [ ] Did you write any **new necessary tests**? (not for typos and docs)
- [ ] Did you verify new and **existing tests pass** locally with your changes?
- [ ] Did you list all the **breaking changes** introduced by this pull request?
- [ ] Did you **update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)**? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review

Anyone in the community is welcome to review the PR.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

- [x] Is this pull request ready for review? (if not, please submit in draft mode)
- [x] Check that all items from **Before submitting** are resolved
- [x] Make sure the title is self-explanatory and the description concisely explains the PR
- [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?

Make sure you had fun coding 🙃

2022-03-16 18:29 UTC, rohitgr7 commented on pytorch_lightning/core/lightning.py
> +        self.trainer: Optional[Trainer] = None
```suggestion
        self.trainer: Optional["pl.Trainer"] = None
```
I'd rather do and remove the import

2022-03-19 19:41 UTC, awaelchli approved these changes

2022-03-21 17:20 UTC, Borda approved these changes

2022-03-21 17:21 UTC, carmocca requested changes
Please ping me when the mypy job is green!

Thank you for your work.

2022-03-25 13:22 UTC, jlhbaseball15 commented on pytorch_lightning/core/lightning.py
> +        self.trainer: Optional["pl.Trainer"] = None
Done!

2022-03-25 13:23 UTC, jlhbaseball15 commented
@carmocca Mypy is fixed!

2022-03-25 16:44 UTC, carmocca approved these changes

2022-03-25 17:56 UTC, carmocca commented on pytorch_lightning/overrides/distributed.py
> +    def sampler(self) -> Union[Sampler, Iterable]:
It's the type defined in torch's `BatchSampler`:

`    def __init__(self, sampler: Union[Sampler[int], Iterable[int]], batch_size: int, drop_last: bool) -> None:
`

2022-03-29 04:14 UTC, merged