Make PyTorch Lightning PEP 561 Compliant
PyTorchLightning/pytorch-lightning pull request #3187
Opened 2020-08-26 07:02 UTC by MarioIshac

Fixes [#3186](https://github.com/PyTorchLightning/pytorch-lightning/issues/3186) by adding a `py.typed` under package `pytorch_lightning` and distributing it as part of package data in `setup.py`.

2020-08-26 09:13 UTC, MarioIshac commented
I made this `[WIP]` cause of the 2 cancelled checks, does that mean they failed or is it something else?

2020-08-26 09:20 UTC, Borda commented
> I made this `[WIP]` cause of the 2 cancelled checks, does that mean they failed or is it something else?

no need to add wip in such case, we do not merge anything which is not passing checks :]
the wip means that it may look complete but the author wants to add something extra or he was asked for it so no one would merge it in the meantime of these changes...

2020-08-26 09:21 UTC, Borda requested changes

2020-08-26 09:21 UTC, Borda commented on setup.py
> +    package_data={
move this to MANFEST.in

2020-09-09 15:07 UTC, Borda approved these changes
LGTM

2020-09-09 17:31 UTC, rohitgr7 approved these changes

2020-09-09 17:37 UTC, merged