Changed LearningRateLogger to LearningRateMonitor
PyTorchLightning/pytorch-lightning pull request #3251
Opened 2020-08-28 20:58 UTC by rohitgr7

## What does this PR do?

Changed `LearningRateLogger` to `LearningRateMonitor`. Discussion: https://github.com/PyTorchLightning/pytorch-lightning/pull/3008#issuecomment-675888975

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

2020-08-29 16:37 UTC, awaelchli commented
@rohitgr7 I think we need to make sure that LearningRateLogger can still be used, so maybe subclass 
```
class LearningRateLogger(LearningRateMonitor):
    def __init__(self, *args, **kwargs)
        # print a deprecation warning here
        super().__init__(*args, **kwargs)
```

2020-08-29 17:34 UTC, rohitgr7 commented
Also, should we consider the `row_log_interval` here, just like for usual logs?

2020-08-29 18:55 UTC, awaelchli approved these changes
LGTM, maybe ask @Borda to check deprecation stuff :)

2020-08-29 18:56 UTC, awaelchli commented
> Also, should we consider the row_log_interval here, just like with usual logs?

probably, yes, in new PR?

2020-08-29 19:02 UTC, Borda commented
> LGTM, maybe ask @Borda to check deprecation stuff :)

yeah, this will be quite tricky, there are a few things you need to do:
- keep the original file and reimport `from new.package.path import NewClass as OldClass`
- add deprecation warning to the old file
- add a test that with calling the old class the deprecation warning is raised

2020-08-29 19:03 UTC, Borda requested changes
need to maintain back compatibility... see https://github.com/PyTorchLightning/pytorch-lightning/pull/3251#issuecomment-683330124

2020-08-29 23:56 UTC, rohitgr7 commented
> > Also, should we consider the row_log_interval here, just like with usual logs?

>probably, yes, in new PR?
ok, will add for both LearningRateMonitor and GPUStatsMonitor in a separate one.

2020-08-31 18:21 UTC, rohitgr7 commented
@Borda can you check if the depreciation is done correctly as you asked :) Thanks!

2020-09-01 09:21 UTC, SkafteNicki approved these changes
LGTM

2020-09-01 09:51 UTC, Borda commented on pytorch_lightning/callbacks/lr_logger.py
> +                       " and this will be removed in v0.10.0", DeprecationWarning)
```suggestion
                       " and this will be removed in v0.11.0", DeprecationWarning)
```

2020-09-01 09:51 UTC, Borda commented on tests/callbacks/test_lr_monitor.py
> +def test_lr_logger_deprecated(tmpdir):
pls, move this to file with testing deprecated staff... later much easier to find

2020-09-02 20:40 UTC, rohitgr7 commented
@Borda can you review this? Thanks

2020-09-03 09:24 UTC, Borda approved these changes

2020-09-03 18:17 UTC, merged