[Draft] Fix early stopping without val step when using return dict
PyTorchLightning/pytorch-lightning pull request #3347
Opened 2020-09-04 11:08 UTC by Lucas-Steinmann

## What does this PR do?

Fixes #3199 

In the first commit, I fixed the test, which should check that early stopping works if no val step is executed and a return dict is used.

The second commit, fixes the bug, by checking the ``self.monitor`` key and not only the ``on_early_stop`` key.

This unveiled another bug in the decision whether early stopping is already done based on validation results.
The earlier code, checked for one key specifically. But since any key could be in validation, it is not possible to derive from the key, whether early stopping is done based on validation results. 

Therefore, in the third commit, I used a instance variable as flag to indicate whether early stopping is done based on validation results. The flag is set in ``on_validation_epoch_end`` which is executed before ``on_train_epoch_end``.
Lastly, I added a test which asserts that any key could be used during validation (this would have failed, if I just extended the list of keys to check besides ``val_on_early_stop``).

What remains to be done, is to update the docs. There has been discussion before, hence I will add each change as a separate commit and you can deny or allow each on its own.

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

2020-09-15 16:56 UTC, teddykoker commented
Great work! LGTM 👍

2020-09-15 23:05 UTC, teddykoker approved these changes

2020-09-16 18:28 UTC, nateraw approved these changes
LGTM

2020-09-16 18:28 UTC, nateraw commented on pytorch_lightning/callbacks/early_stopping.py
> +        # Indicates, if eval results are used as basis for early stopping
thx for the comment ❤️

2020-09-16 18:31 UTC, nateraw requested changes
Whoops, didn't notice a couple things...

1. gotta get code style passing
2. double check drone to make sure this works on multiple gpus. seems to failing on results. not sure if this is related to this PR or not

2020-09-18 05:49 UTC, nateraw approved these changes
nevermind, seems issues are unrelated. lets get this merged

2020-09-18 09:28 UTC, SkafteNicki approved these changes
LGTM

2020-09-18 12:51 UTC, Borda commented on tests/callbacks/test_early_stopping.py
> +    assert trainer.current_epoch == 5, 'early_stopping failed'
```suggestion
    assert trainer.current_epoch >= 5, 'early_stopping failed'
```

2020-09-18 12:53 UTC, Borda commented on tests/callbacks/test_early_stopping.py
> +    """
```suggestion
    """Tests whether early stopping works with a custom key and dictionary results on val step."""
```

2020-09-18 12:53 UTC, Borda approved these changes

2020-09-18 21:08 UTC, merged