Fix yaml deprecation
PyTorchLightning/pytorch-lightning pull request #3357
Opened 2020-09-05 09:24 UTC by DSergiu

## What does this PR do?

`yaml.load()` is deprecated as stated here https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

Replaced with `yaml.safe_load()`.

Fixes # (issue)

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [x] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

2020-09-05 11:52 UTC, Borda approved these changes

2020-09-05 16:22 UTC, rohitgr7 approved these changes

2020-09-05 21:42 UTC, awaelchli approved these changes

2020-09-07 05:31 UTC, justusschock requested changes
Do we really want (de-)serialisation of arbitrary objects? We aren't saving checkpoints with it, so I don't think so. In that case we should possibly go with `safe_load` (https://stackoverflow.com/questions/1773805/how-can-i-parse-a-yaml-file-in-python)

2020-09-07 06:20 UTC, DSergiu commented
`The function yaml.safe_load limits this ability to simple Python objects like integers or lists.`
There are plenty of tests which will break if using `safe_load`. They are testing loading complex data for `hparams.yaml`.
@justusschock

2020-09-07 06:32 UTC, awaelchli commented
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation 
states that full_load has safe loading included, so no unsafe code execution.

2020-09-07 07:51 UTC, justusschock approved these changes

2020-09-07 07:58 UTC, Borda approved these changes

2020-09-07 08:00 UTC, merged