Get experiment_id from MLFlow only once instead of each training loop.
PyTorchLightning/pytorch-lightning pull request #3394
Opened 2020-09-08 11:05 UTC by patrickorlando

## What does this PR do?
When using the MLFLow logger, the MLFLow client retrieves the experiment id from the MLFlowClient each time `logger.experiment` is called/accessed. This causes overhead during training and validation loops which is dramatic if the server is remote. 

This PR checks whether the experiment_id is already defined (meaning it has already been retrieved) and does not make the call to MLFlow if so.

Fixes #3393 

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

2020-09-08 17:30 UTC, rohitgr7 approved these changes
LGTM.

2020-09-08 17:30 UTC, rohitgr7 commented on pytorch_lightning/loggers/mlflow.py
>          if not self._run_id:
```suggestion
        if self._experiment_id is None:
            expt = self._mlflow_client.get_experiment_by_name(self._experiment_name)
            if expt is not None:
                self._experiment_id = expt.experiment_id
            else:
                log.warning(f'Experiment with name {self._experiment_name} not found. Creating it.')
                self._experiment_id = self._mlflow_client.create_experiment(name=self._experiment_name)

        if self._run_id is None:
```

2020-09-08 22:16 UTC, Borda approved these changes
LGTM

2020-09-09 07:19 UTC, awaelchli commented
@patrickorlando This tests fails on master, could you add it to the file tests/loggers/test_mlflow.py ?

```python
def test_mlflow_created_once(tmpdir):
    logger = MLFlowLogger('test', save_dir=tmpdir)
    get_experiment_name = logger.experiment.get_experiment_by_name
    with mock.patch.object(MlflowClient, 'get_experiment_by_name', wraps=get_experiment_name) as mocked:
        _ = logger.experiment
        _ = logger.experiment
        _ = logger.experiment
        assert mocked.call_count == 1
```

Thanks

2020-09-09 07:20 UTC, awaelchli requested changes
requesting a test to make the bugfix complete, see my comment above

2020-09-09 07:47 UTC, patrickorlando commented
@awaelchli I've added the test case, but I had to change
```
get_experiment_name = logger.experiment.get_experiment_by_name
```
to 
```
get_experiment_name = logger._mlflow_client.get_experiment_by_name
```
It had already been called in the first case before it was mocked and the test was failing.

I've checked that this change still fails on master. `commit: d438ad8a8db3e76d3ed4e3c6bc9b91d6b3266b8e`
```
    def test_mlflow_experiment_id_retrieved_once(tmpdir):
        logger = MLFlowLogger('test', save_dir=tmpdir)
        get_experiment_name = logger._mlflow_client.get_experiment_by_name
        with mock.patch.object(MlflowClient, 'get_experiment_by_name', wraps=get_experiment_name) as mocked:
            _ = logger.experiment
            _ = logger.experiment
            _ = logger.experiment
>           assert mocked.call_count == 1
E           AssertionError: assert 3 == 1
E            +  where 3 = <MagicMock name='get_experiment_by_name' id='140215984767184'>.call_count

tests/loggers/test_mlflow.py:53: AssertionError
```

2020-09-09 07:52 UTC, pep8speaks commented
Hello @patrickorlando! Thanks for updating this PR. 



* In the file [`tests/loggers/test_mlflow.py`](https://github.com/PyTorchLightning/pytorch-lightning/blob/d01be533e750393d1798038f5cea4f3e308bb736/tests/loggers/test_mlflow.py):

> [Line 46:1](https://github.com/PyTorchLightning/pytorch-lightning/blob/d01be533e750393d1798038f5cea4f3e308bb736/tests/loggers/test_mlflow.py#L46): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 53:38](https://github.com/PyTorchLightning/pytorch-lightning/blob/d01be533e750393d1798038f5cea4f3e308bb736/tests/loggers/test_mlflow.py#L53): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2020-09-09 08:04 UTC, awaelchli commented
oh I see, because I had it added to the top of the file. But this way is better 👍

2020-09-09 08:10 UTC, awaelchli approved these changes

2020-09-09 09:38 UTC, merged