`training_epoch_end Results [WIP]
PyTorchLightning/pytorch-lightning pull request #3530
Opened 2020-09-17 17:23 UTC by teddykoker

## What does this PR do?

Fixes #3356 

# Before submitting

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

2020-09-17 18:15 UTC, teddykoker commented
The issue here is with assigning attributes to `TrainResults`:
```python
def training_step(self, batch, batch_idx):
    x, y = batch
    y_hat = self(x)
    loss = F.cross_entropy(y_hat, y)
    result = TrainResult(minimize=loss)
    result.log_dict({"train_loss": loss})

    result.y = y
    result.y_hat = y_hat
    return result

def training_epoch_end(self, out):
    epoch_loss = F.cross_entropy(out.y_hat, out.y)
    result = TrainResult()
    result.log_dict({"train_epoch_loss": epoch_loss})
    return result
```
This should work (as shown in the docs)

2020-09-17 18:36 UTC, teddykoker commented
These are the important changes 
https://github.com/PyTorchLightning/pytorch-lightning/pull/3530/files#diff-9471ab95794bb8e572901942af92359eL319-L349

2020-09-17 18:37 UTC, teddykoker commented on pytorch_lightning/core/step_result.py
> +                    meta[name]["value"] = padded
These are the changes

2020-09-17 18:39 UTC, teddykoker commented on pytorch_lightning/core/step_result.py
> +
This is the biggest change, user assigned attributes must be collated separately as they are not in the `meta` dict.

2020-09-17 18:42 UTC, Borda commented
@teddykoker could you please set your Balck to ignore ' and " with `-S, --skip-string-normalization`

2020-09-17 20:53 UTC, pep8speaks commented
Hello @teddykoker! Thanks for updating this PR. 

* In the file [`pytorch_lightning/core/step_result.py`](https://github.com/PyTorchLightning/pytorch-lightning/blob/745442334db153a3767e5757bb3b06a4a3a1e729/pytorch_lightning/core/step_result.py):

> [Line 347:1](https://github.com/PyTorchLightning/pytorch-lightning/blob/745442334db153a3767e5757bb3b06a4a3a1e729/pytorch_lightning/core/step_result.py#L347): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-09-19 17:54 UTC, teddykoker commented
Truncated back propagation through time works failing ..., still WIP

2020-09-25 11:41 UTC, Borda requested changes
pls simplify the tests...

2020-09-25 11:41 UTC, Borda commented on tests/core/test_results.py
> +    class LitModel(LightningModule):
How this differs from our `EvalModelTemplate`, pls write just the methods which differ...

2020-09-25 11:41 UTC, Borda commented on pytorch_lightning/core/step_result.py
> +                if name not in {'checkpoint_on', 'early_stop_on', 'minimize'} and name in meta:
```suggestion
                is_reserved = name in {'checkpoint_on', 'early_stop_on', 'minimize'}
                if not is_reserved and name in meta:
```

2020-10-01 00:04 UTC, edenlightning commented
@teddykoker should we kill it?

2020-10-01 00:38 UTC, teddykoker commented
@edenlightning lemme double check this isn’t necessary for the new log api otherwise I’ll kill it

2020-10-06 18:29 UTC, closed without merging