Skip replacing dataloader sampler if it's already a distributed sampler
PyTorchLightning/pytorch-lightning pull request #4273
Opened 2020-10-21 05:52 UTC by ananthsub

## What does this PR do?

Skip replacing dataloader sampler if it's already a distributed sampler. Currently this raises a `MisconfigurationException`. This causes confusion, since `trainer.replace_sampler_ddp` is by default True. In such cases, we can silently skip replacing the sampler instead of failing

# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [x] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

2020-10-21 06:19 UTC, s-rog commented
Has this change already been approved by one of our team members?
Currently `trainer.replace_sampler_ddp` is supposed to be `False` in this case, and using the default `True` is considered user error.

2020-10-21 09:16 UTC, justusschock approved these changes

2020-10-21 09:17 UTC, justusschock commented
@s-rog while this is true, we still can do that type check and the main idea of that flag is being able to turn it off (which you still can)

2020-10-21 09:48 UTC, SkafteNicki approved these changes

2020-10-21 09:49 UTC, s-rog reviewed
Do we already have a test that covers this new behavior? Otherwise LGTM!

2020-10-21 15:20 UTC, ananthsub commented
@s-rog I'll add one for a dataloader configured with a distributed sampler and `replace_sampler_ddp=True` to confirm it doesn't throw

2020-10-21 15:37 UTC, awaelchli commented
Be careful, with this change, the docs are slightly misleading now. It currently reads:

> Enables auto adding of distributed sampler. By default it will add shuffle=True for train sampler and shuffle=False for val/test sampler. If you want to customize it, you can set replace_sampler_ddp=False and add your own distributed sampler.

2020-10-22 06:15 UTC, awaelchli commented on tests/trainer/test_dataloaders.py
> +        callbacks=[DistribSamplerCallback()]
```suggestion
        callbacks=[DistribSamplerCallback()],
```

2020-10-22 06:17 UTC, s-rog approved these changes

2020-10-22 06:32 UTC, awaelchli commented on tests/trainer/test_dataloaders.py
> +    class ModelWithDataLoaderDistributedSampler(EvalModelTemplate):
hey @ananthsub 
Looks like you need to move this class outside the test function or we get the good old pickling error :)

2020-10-23 10:08 UTC, carmocca commented
LGTM. Great idea!

2020-10-23 10:48 UTC, SeanNaren approved these changes

2020-10-23 11:48 UTC, SeanNaren requested changes
We need to fix the test, seems like its failing on multiple GPUs.

2020-10-23 13:19 UTC, rohitgr7 commented on tests/trainer/test_dataloaders.py
> +            shuffle=False
```suggestion
            shuffle=True
```

2020-10-23 13:46 UTC, rohitgr7 reviewed
just trying.

2020-10-23 13:46 UTC, rohitgr7 commented on tests/trainer/test_dataloaders.py
> +            shuffle=True
```suggestion
            shuffle=False
```

2020-10-23 13:46 UTC, rohitgr7 commented on tests/trainer/test_dataloaders.py
> +        dist_sampler = DistributedSampler(dataloader.dataset, shuffle=False)
```suggestion
        dist_sampler = DistributedSampler(dataloader.dataset, shuffle=True)
```

2020-10-23 14:08 UTC, rohitgr7 commented
I suggest while adding a sampler we should explicitlly set `shuffle=False`[here](https://github.com/PyTorchLightning/pytorch-lightning/blob/3abfec896212ea85e45d6ac3ccb323ef242d16de/pytorch_lightning/trainer/data_loading.py#L138) to avoid the case if the dataloader already has `shuffle=True`.

2020-10-23 14:09 UTC, rohitgr7 approved these changes

2020-10-23 14:18 UTC, SeanNaren approved these changes

2020-10-23 14:21 UTC, SeanNaren commented
@rohitgr7 think we should include that in this PR or handle this separately?

2020-10-23 14:30 UTC, rohitgr7 commented
@SeanNaren either way is fine or let's just do it separately and also here in `_get_distributed_sampler(self, dataloader, train):` this `train` argument should be renamed to `shuffle` for better readability of the code.

2020-10-23 14:46 UTC, rohitgr7 requested changes
please wait

2020-10-23 15:28 UTC, rohitgr7 approved these changes

2020-10-23 16:34 UTC, merged