[Doc] Fix on_train_batch_end description
PyTorchLightning/pytorch-lightning pull request #4330
Opened 2020-10-24 02:45 UTC by amogkam

## What does this PR do?
I believe the outputs arg to on_train_batch_end hook is the result of training_step_end(training_step(x)) not validation_step_end(validation_step(x)). This PR fixes this in the docstring.

Fixes https://github.com/PyTorchLightning/pytorch-lightning/issues/4329

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
 - [x] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.    
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

2020-10-24 03:06 UTC, awaelchli approved these changes

2020-10-24 10:19 UTC, ydcjeff approved these changes

2020-10-24 11:03 UTC, rohitgr7 approved these changes

2020-10-24 11:05 UTC, rohitgr7 requested changes
pls wait. a few more are there I think

2020-10-24 11:10 UTC, rohitgr7 approved these changes

2020-10-24 11:44 UTC, rohitgr7 commented
`[skip ci]` doesn't work anymore? This PR seems to be running gpu tests.

2020-10-24 12:57 UTC, awaelchli commented
> `[skip ci]` doesn't work anymore? This PR seems to be running gpu tests.

I think it is because I added it retrospectively?

2020-10-26 14:33 UTC, tchaton approved these changes

2020-10-26 14:53 UTC, SkafteNicki approved these changes

2020-10-26 14:54 UTC, merged