Disable training when limit_train_batches=0
PyTorchLightning/pytorch-lightning pull request #4371
Opened 2020-10-26 13:50 UTC by rohitgr7

## What does this PR do?

when `limit_train_batches=0`, it still train the model for 1 batch. For now I have disable training completely in such a case, but it can be changed to disablevim epochs instead.

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)

Anyone in the community is free to review the PR once the tests have passed.    
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

2020-10-26 13:50 UTC, pep8speaks commented
Hello @rohitgr7! Thanks for opening this PR. 



* In the file [`pytorch_lightning/trainer/training_loop.py`](https://github.com/PyTorchLightning/pytorch-lightning/blob/14046fe8b0187f795931bc189fa545c87a8b6659/pytorch_lightning/trainer/training_loop.py):

> [Line 79:1](https://github.com/PyTorchLightning/pytorch-lightning/blob/14046fe8b0187f795931bc189fa545c87a8b6659/pytorch_lightning/trainer/training_loop.py#L79): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 86:1](https://github.com/PyTorchLightning/pytorch-lightning/blob/14046fe8b0187f795931bc189fa545c87a8b6659/pytorch_lightning/trainer/training_loop.py#L86): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace





Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2020-10-28 01:38 UTC, s-rog approved these changes
Ran into this issue recently as well!

2020-10-28 09:53 UTC, justusschock approved these changes

2020-10-28 10:18 UTC, SkafteNicki approved these changes

2020-11-02 10:59 UTC, tchaton requested changes
Great PR ! Would you mind using BoringModel ?

2020-11-02 10:59 UTC, tchaton commented on tests/trainer/test_trainer.py
> +    class CurrentModel(EvalModelTemplate):
Can you use BoringModel ?

2020-11-02 18:44 UTC, rohitgr7 commented on tests/trainer/test_trainer.py
> +    class CurrentModel(EvalModelTemplate):
done.

2020-11-02 20:18 UTC, tchaton approved these changes
Great catch !

2020-11-03 06:40 UTC, merged