Add  williamfalcon as owner for API changes
PyTorchLightning/pytorch-lightning pull request #4610
Opened 2020-11-10 21:39 UTC by edenlightning

Add williamfalcon's approval for API changes.

2020-11-10 21:42 UTC, teddykoker commented
Pretty sure this won't do anything as everyone still owns `*`

2020-11-10 21:43 UTC, teddykoker requested changes

2020-11-10 21:43 UTC, teddykoker commented on .github/CODEOWNERS
> +/pytorch_lightning/core/hooks.py.     @williamfalcon
```suggestion
/pytorch_lightning/core/hooks.py     @williamfalcon
```

2020-11-10 23:34 UTC, edenlightning commented
![Screenshot - 2020-11-10T183323 507](https://user-images.githubusercontent.com/66261195/98746318-40d01a00-2383-11eb-9c4f-73438d16057c.png)

then this doesn't make sense, no?

2020-11-10 23:58 UTC, williamFalcon commented
doesn’t this also make it so that i have to approve in addition to the * people? for these files?

2020-11-11 01:45 UTC, edenlightning commented
"The last matching pattern has the most precedence" (see [this](https://docs.github.com/en/enterprise-server@2.20/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax)).

I'm just wondering if it means it will assign **only** you to review. Not clear on that. Any idea?

2020-11-11 08:59 UTC, Borda reviewed
Will is already in all revies as default do what does this change shall add?
just a note, this also included all bug-fixed in theses files, not design/APi changes

2020-11-11 14:13 UTC, edenlightning commented
@Borda do you know if we can make him required somehow only for these files? but not the only one?

2020-11-15 15:53 UTC, merged

2020-11-15 15:55 UTC, williamFalcon commented
let's add this for now and figure out changes later.

the behavior that i would love is:
for certain files i need to be an additional approver.

ie: if person modified lightning.py, then the standard reviewers apply. In addition, my approval is required.