[WIP] Metrics as autosummary tables
PyTorchLightning/pytorch-lightning pull request #4774
Opened 2020-11-19 13:19 UTC by SkafteNicki

## What does this PR do?

Reformat metric docs to use autosummary.
Requested by @tchaton on slack :]

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In in short, see following bullet-list:  

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified; _Bugfixes should be including in bug-fix release milestones (m.f.X) and features should be included in (m.X.b) releases._
 

## Did you have fun?
Make sure you had fun coding 🙃

2020-11-19 14:58 UTC, ydcjeff commented on docs/source/metrics.rst
> +    :template: classtemplate.rst
```suggestion
    :template: functiontemplate.rst
```

2020-11-19 14:58 UTC, ydcjeff commented on docs/source/metrics.rst
> +    :template: classtemplate.rst
```suggestion
    :template: functiontemplate.rst
```

2020-11-19 14:58 UTC, ydcjeff commented on docs/source/metrics.rst
> +    :template: classtemplate.rst
```suggestion
    :template: functiontemplate.rst
```

2020-11-19 17:10 UTC, Borda reviewed
can we add screenshot of the new one?

2020-11-20 07:29 UTC, SkafteNicki commented
![Untitled](https://user-images.githubusercontent.com/24896311/99772085-6a6b0d00-2b0a-11eb-98c7-f6b9682cab11.png)

2020-11-20 07:32 UTC, ananyahjha93 approved these changes

2020-11-20 07:33 UTC, ydcjeff approved these changes

2020-11-20 09:22 UTC, tchaton approved these changes
Hey @SkafteNicki, looks great ! Thanks !

2020-11-20 09:41 UTC, rohitgr7 approved these changes
LGTM. Just some comments.

2020-11-20 09:41 UTC, rohitgr7 commented on docs/source/metrics.rst
> +    you should very rearly have to call ``reset()`` yourself.
```suggestion
    you should very rarely have to call ``reset()`` yourself.
```

2020-11-20 09:41 UTC, rohitgr7 commented on docs/source/metrics.rst
> +****************
```suggestion
*************
Class metrics
*************
```

2020-11-20 09:41 UTC, rohitgr7 commented on docs/source/metrics.rst
> +    ConfusionMatrix
```suggestion
    Accuracy
    ConfusionMatrix
    Fbeta
    Precision
    Recall
```
alphabetical order maybe?

2020-11-20 09:41 UTC, rohitgr7 commented on docs/source/metrics.rst
> +    SSIM
```suggestion
    ExplainedVariance
    MeanAbsoluteError
    MeanSquaredLogError
    MeanSquaredError
    PSNR
    SSIM
```
alphabetical order maybe?

2020-11-20 09:41 UTC, rohitgr7 commented on docs/source/metrics.rst
> +best integration and user experience, please consider also to use the class interface.
```suggestion
best integration and user experience, please consider to use the class interface.
```

2020-11-20 09:41 UTC, rohitgr7 commented on docs/source/metrics.rst
> +    ssim
```suggestion
    explained_variance
    mean_absolute_error
    mean_squared_log_error
    mean_squared_error
    psnr
    ssim
```

2020-11-20 09:41 UTC, rohitgr7 commented on docs/source/metrics.rst
> +    to_onehot
```suggestion
    accuracy
    auc
    auroc
    average_precision
    confusion_matrix
    dice_score
    f1_score
    fbeta_score
    iou
    multiclass_auroc
    multiclass_roc
    precision
    precision_recall
    precision_recall_curve
    recall
    roc
    stat_scores
    stat_scores_multiple_classes
    to_categorical
    to_onehot
```

2020-11-20 10:10 UTC, williamFalcon requested changes
before merging can i clarify something?

the metric summary tables remove the menus on the right that make it super easy to search for stuff without having to scroll endlessly through the page. 

is that menu gone now?

if so, can we undo all these summary tables? they make quickly scanning to see what’s available impossible. 

to see how useful this menu is, try finding any trainer flag. now imagine if the menu ok the right didn’t exist and you instead had to scroll the full page just to see what flags are available. 

remember that our docs are as much about discovery as they are about referencing

2020-11-20 10:40 UTC, SkafteNicki commented
The menu is not all gone, it still expands to the individual types of metrics:
![Untitled2](https://user-images.githubusercontent.com/24896311/99790843-f7bb5b00-2b24-11eb-92ac-be051f63ef9d.png)
If the user is aware what type of metric they are looking for (classification, regression, ect) I would argue that it requires much less scrolling now.

2020-11-20 11:07 UTC, williamFalcon commented
right. this is exactly what i think is not a great user experience. 

we now remove the ability for the user to discover what is available by just glancing at the right since all the metrics are gone from the menu. 

i also want to remove these tables from the rest of the docs. 

this approach assumes people know what they are looking for but makes it impossible for people who are just browsing to see what’s available... and actually the menu on the right showing the list of metrics is much much faster to find the metric you are looking for. 

@tchaton, @edenafek can we remove these tables from the docs and do it exactly like we do for trainer flags?

2020-11-20 11:52 UTC, tchaton commented
Hey @SkafteNicki, 

After chatting with Will, 
we thought it is better to keep the Metric as they are, but make the right slide panel bigger instead and take inspiration from Trainer.

I deeply apologise as you invested time working on this and it won't get integrated.
I will be very careful when suggesting this kind of changes in the future.

Best regards,
Thomas Chaton.

2020-11-20 12:09 UTC, SkafteNicki commented
@tchaton it is completely fine, I did not spend that much time on this PR :]
Closing this pr.

2020-11-20 12:09 UTC, closed without merging