Fix docs typo
PyTorchLightning/pytorch-lightning pull request #4930
Opened 2020-12-01 09:22 UTC by siahuat0727

## What does this PR do?

Fixes docs typo

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together? Otherwise, we ask you to create a separate PR for every change.
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:  

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified; _Bugfixes should be including in bug-fix release milestones (m.f.X) and features should be included in (m.X.b) releases._
 

## Did you have fun?
Make sure you had fun coding 🙃

2020-12-03 09:01 UTC, tchaton approved these changes
LTGM !

2020-12-03 09:06 UTC, ydcjeff approved these changes

2020-12-03 10:14 UTC, Borda approved these changes

2020-12-03 21:58 UTC, awaelchli approved these changes

2020-12-20 21:11 UTC, Borda requested changes
mind check the failing docs examples?

2020-12-20 21:39 UTC, awaelchli approved these changes
@Borda this failing gpu test comes from master

2021-01-26 23:19 UTC, Borda approved these changes

2021-01-26 23:19 UTC, Borda commented on docs/source/style_guide.rst
>              self.layer_3 = nn.Linear(...)
```suggestion
            self.layer_2 = nn.Linear()
            self.layer_3 = nn.Linear()
```

2021-01-26 23:19 UTC, Borda commented on docs/source/style_guide.rst
> +        def __init__(self, encoder: nn.Module, coef_x: float = 0.2, lr: float = 1e-3):
```suggestion
        def __init__(self, encoder: nn.Module, coef_x: float = 0.2, lr: float = 1e-3):
            pass
```

2021-01-28 09:22 UTC, Borda commented on docs/source/style_guide.rst
>      class LitModel(pl.LightningModule):
```suggestion
    class LitModel(LightningModule):
```

2021-01-28 09:22 UTC, Borda commented on docs/source/style_guide.rst
>      class LitModel(pl.LightningModule):
```suggestion
    class LitModel(LightningModule):
```

2021-01-29 10:19 UTC, Borda commented on docs/source/style_guide.rst
>              self.layer_1 = nn.Linear(...)
```suggestion
            self.layer_1 = nn.Linear()
```

2021-02-01 13:09 UTC, merged