fix some minor typos in docs
PyTorchLightning/pytorch-lightning pull request #5369
Opened 2021-01-05 23:44 UTC by Borda

## What does this PR do?

minor typos:
- arg names do not match docs
- arguments in docs are not a member of the func

## Before submitting
- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes [if needed]?
- [ ] Did you write any new necessary tests [no need for typos, docs]? 
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)?

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:  

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [ ] **Check that target branch and milestone are aligned!**
 

## Did you have fun?
Make sure you had fun coding 🙃

2021-01-06 03:35 UTC, marload requested changes
On small request changes 😄

2021-01-06 03:35 UTC, marload commented on pytorch_lightning/overrides/data_parallel.py
> +def parallel_apply(modules: Module, inputs: Tensor, kwargs_tup: tuple = None, devices: list = None):  # pragma: no-cover
`Optional[tuple]`, `Optional[list]` looks better.

2021-01-06 08:23 UTC, Borda commented on pytorch_lightning/overrides/data_parallel.py
```suggestion
from typing import Optional

```

2021-01-06 08:24 UTC, pep8speaks commented
Hello @Borda! Thanks for updating this PR. 































* In the file [`pytorch_lightning/overrides/data_parallel.py`](https://github.com/PyTorchLightning/pytorch-lightning/blob/42bc6ef8fd53fae5895aff4882cb298c3390c2c4/pytorch_lightning/overrides/data_parallel.py):

> [Line 227:121](https://github.com/PyTorchLightning/pytorch-lightning/blob/42bc6ef8fd53fae5895aff4882cb298c3390c2c4/pytorch_lightning/overrides/data_parallel.py#L227): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (140 > 120 characters)

2021-01-06 10:58 UTC, marload approved these changes

2021-01-06 11:52 UTC, SkafteNicki approved these changes

2021-01-06 12:10 UTC, ydcjeff approved these changes

2021-01-07 00:13 UTC, carmocca approved these changes

2021-01-07 00:53 UTC, s-rog approved these changes

2021-01-07 10:58 UTC, justusschock approved these changes

2021-01-07 10:58 UTC, SeanNaren approved these changes

2021-01-07 13:01 UTC, merged