[feat] 2/2 Add auto-id for trainer.predict output
PyTorchLightning/pytorch-lightning pull request #5599
Opened 2021-01-21 08:32 UTC by tchaton

## What does this PR do?

This PR adds `auto-id` on top of Trainer.predict

Fixes # (issue) <- this [links related issue to this PR](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [ ] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

2021-01-21 08:32 UTC, pep8speaks commented
Hello @tchaton! Thanks for opening this PR. 





































* In the file [`pytorch_lightning/trainer/data_loading.py`](https://github.com/PyTorchLightning/pytorch-lightning/blob/07222e70c0d0610e7b7db8a6a80e1f444a8466af/pytorch_lightning/trainer/data_loading.py):

> [Line 115:20](https://github.com/PyTorchLightning/pytorch-lightning/blob/07222e70c0d0610e7b7db8a6a80e1f444a8466af/pytorch_lightning/trainer/data_loading.py#L115): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'

























* In the file [`tests/trainer/test_supporters.py`](https://github.com/PyTorchLightning/pytorch-lightning/blob/07222e70c0d0610e7b7db8a6a80e1f444a8466af/tests/trainer/test_supporters.py):

> [Line 239:29](https://github.com/PyTorchLightning/pytorch-lightning/blob/07222e70c0d0610e7b7db8a6a80e1f444a8466af/tests/trainer/test_supporters.py#L239): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'



Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2021-01-25 20:14 UTC, williamFalcon requested changes

2021-01-25 20:14 UTC, williamFalcon commented on pytorch_lightning/trainer/supporters.py
> +                "HINT: use Trainer(enable_predict_auto_id=False) and provide your own id."
i don't know what this does....
can you rename the flag to make it clear? or add docstrings or a much clearer error message?

2021-01-25 20:14 UTC, williamFalcon commented on pytorch_lightning/trainer/trainer.py
> +            enable_predict_auto_id: Explicitly enables or disables sampler replacement.
what does a sampler have to do with predict?

2021-01-29 09:40 UTC, Borda commented
@tchaton how is it going here? probably need some large rebase :]

2021-02-02 11:02 UTC, closed without merging