[WIP] Convert progress bar metrics to float
PyTorchLightning/pytorch-lightning pull request #5692
Opened 2021-01-28 12:12 UTC by carmocca

## What does this PR do?

# Fixes 5481

Will probably include some refactors. Opening this PR to run tests

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [x] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [ ] **Check that target branch and milestone match!**

2021-01-28 12:51 UTC, tchaton approved these changes

2021-01-29 09:26 UTC, Borda commented
@carmocca is it still WIP or ready to go? :]

2021-01-29 13:18 UTC, carmocca commented
So I planned to include a larger refactor here. I think i'll commit the one-line fix to master and work on the refactor here.

2021-01-29 13:30 UTC, Borda commented
> So I planned to include a larger refactor here. I think i'll commit the one-line fix to master and work on the refactor here.

I would rather have multiple smaller refactors, it is easier to review :]

2021-02-03 01:34 UTC, carmocca commented on tests/callbacks/test_progress_bar.py
> +def test_test_progress_bar_thing(tmpdir):
```suggestion
def test_tensor_to_float_conversion(tmpdir):
```

2021-02-04 00:27 UTC, s-rog approved these changes

2021-02-04 18:05 UTC, Borda approved these changes

2021-02-04 19:13 UTC, awaelchli reviewed
Just one request: could we move the test to the logging tests? Because the conversion doesn't happen in the progress bar therefore I propose to move this test outside the progress bar unit tests.

2021-02-04 19:17 UTC, Borda requested changes
pls see https://github.com/PyTorchLightning/pytorch-lightning/pull/5692#pullrequestreview-583728293

2021-02-04 20:13 UTC, carmocca commented
> Just one request: could we move the test to the logging tests? Because the conversion doesn't happen in the progress bar therefore I propose to move this test outside the progress bar unit tests.

I disagree. The purpose of the test is to check that the progress bar correctly displays the number as a float, not a tensor. The fact that the fix is in the logger connector is independent to what we want to fix. If the logger connector was completely replaced by a different abstraction, I still want to make sure the progress bar does not change.

2021-02-04 21:00 UTC, awaelchli approved these changes
I am not convinced with your argument but it's ok I don't want to block. If we change our mind we can move the test later.

2021-02-10 23:34 UTC, carmocca commented on tests/callbacks/test_progress_bar.py
> +    class TestModel(BoringModel):
```suggestion

    class TestModel(BoringModel):

```

2021-02-11 00:16 UTC, merged