Fix logic error in Apex AMP
PyTorchLightning/pytorch-lightning pull request #5995
Opened 2021-02-15 23:34 UTC by SeanNaren

## What does this PR do?

Within the accelerator refactor there is a small error in the Apex logic, which results in us not calling `optimizer.step` in automatic optimization. This logic should be reversed

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified
 - [ ] **Check that target branch and milestone match!**

## Did you have fun?
Make sure you had fun coding 🙃

2021-02-15 23:38 UTC, awaelchli approved these changes

2021-02-15 23:45 UTC, carmocca approved these changes

2021-02-16 00:03 UTC, Borda approved these changes

2021-02-16 08:11 UTC, justusschock approved these changes

2021-02-16 08:47 UTC, tchaton reviewed
It should call optimizer.step for both manual and automatic.

2021-02-16 08:47 UTC, tchaton commented on pytorch_lightning/plugins/precision/apex_amp.py
> +        if pl_module.automatic_optimization:
```suggestion
    def pre_optimizer_step(
        self, pl_module: LightningModule, optimizer: Optimizer, optimizer_idx: int, lambda_closure: Callable, **kwargs
    ) -> bool:
        """
        always called before the optimizer step.
        """
        # apex amp does not support closures.
        lambda_closure()

        if not pl_module.automatic_optimization:
            pl_module.trainer.call_hook("on_after_backward")
        
        optimizer.step()

        return False
```

2021-02-16 08:47 UTC, tchaton commented on pytorch_lightning/plugins/precision/apex_amp.py
> +        if pl_module.automatic_optimization:
The pl_module.trainer.call_hook("on_after_backward") hook is already being called elsewhere in automatic_optimization.

2021-02-16 08:48 UTC, tchaton requested changes
Need to be called for both

2021-02-16 14:57 UTC, tchaton approved these changes
LGTM !

2021-02-16 19:05 UTC, merged