Adds more early stopping options
PyTorchLightning/pytorch-lightning pull request #6232
Opened 2021-02-26 19:55 UTC by jlperla

Adds two new features to the EarlyStopping callback:
- an optional `max_time` .  If the elapsed time of execution (calculated from the starting time of callback creation) ever goes above `max_time`, then it stops
- an optional `threshold`.  If the monitored value ever hits the threshold (where the direction of the comparison is consistent with the `mode`) then it stops.

In addition, it displays the reason for early stopping if `verbose = true`.

@williamFalcon  This is what we discussed.  Sorry, I tried to create some of the tests but I am not a competent enough python programmer to figure out how to even run them in vscode!  I was able to test this in my current setup for the key variations, but the things I wasn't able to effectively test were the multi-processor stuff and the saving/loading of checkpoints.  The code was setup to make that  checkpoint saving/loading possible, but that is the only non-trivial logic.

In essence, what it does is have an `elapsed` time which is stores, and it sets the `self.last_time` both on construction and when loading a checkpoint.   Hopefully that logic is correct.

2021-02-26 19:55 UTC, pep8speaks commented
Hello @jlperla! Thanks for opening this PR. 

* In the file [`pytorch_lightning/callbacks/early_stopping.py`](https://github.com/PyTorchLightning/pytorch-lightning/blob/3471df8361286cc99ead6f422598f20f76a1ed1d/pytorch_lightning/callbacks/early_stopping.py):

> [Line 138:41](https://github.com/PyTorchLightning/pytorch-lightning/blob/3471df8361286cc99ead6f422598f20f76a1ed1d/pytorch_lightning/callbacks/early_stopping.py#L138): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 188:30](https://github.com/PyTorchLightning/pytorch-lightning/blob/3471df8361286cc99ead6f422598f20f76a1ed1d/pytorch_lightning/callbacks/early_stopping.py#L188): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 192:18](https://github.com/PyTorchLightning/pytorch-lightning/blob/3471df8361286cc99ead6f422598f20f76a1ed1d/pytorch_lightning/callbacks/early_stopping.py#L192): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 195:29](https://github.com/PyTorchLightning/pytorch-lightning/blob/3471df8361286cc99ead6f422598f20f76a1ed1d/pytorch_lightning/callbacks/early_stopping.py#L195): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 199:18](https://github.com/PyTorchLightning/pytorch-lightning/blob/3471df8361286cc99ead6f422598f20f76a1ed1d/pytorch_lightning/callbacks/early_stopping.py#L199): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 201:39](https://github.com/PyTorchLightning/pytorch-lightning/blob/3471df8361286cc99ead6f422598f20f76a1ed1d/pytorch_lightning/callbacks/early_stopping.py#L201): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)

2021-02-26 20:23 UTC, edenlightning commented
Thanks for creating the PR @jlperla! I think threshold is great, but max_time maybe would be better as a separate trainer flag? 

@PyTorchLightning/core-contributors thoughts?

2021-02-26 20:32 UTC, rohitgr7 commented
> Thanks for creating the PR @jlperla! I think threshold is great, but max_time maybe would be better as a separate trainer flag?
> 
> @PyTorchLightning/core-contributors thoughts?

`max_time` can be configured in a separate callback.

2021-02-26 20:44 UTC, jlperla commented
> Thanks for creating the PR @jlperla! I think threshold is great, but max_time maybe would be better as a separate trainer flag?
> 
> @PyTorchLightning/core-contributors thoughts?
I have no opinion on `max_time` in the trainer vs. a callback.  Probably in the trainer if it is possible.

Just one of them quickly and robustly!  Especially when running on cloud jobs where you are worried to go to sleep just in case  your code won't stop correctly and you will burn through your AWS budget for no good reason for your 50 different simulateous GPU experiments.

> max_time can be configured in a separate callback as per user requirements.
As discussed, I don't care where the feature is, but would prefer it to be central to the setup since it seems symmetric with `max_epochs`.

The one caution I have is that I don't think having interacting callbacks all doing early-stopping is robust.  The issue I uncovered a few days ago in lightning is a testament to how difficult it is to coordinate this stuff---especially if we are thinking about distributed setups.

2021-02-28 18:11 UTC, simonmAsh26 approved these changes

2021-03-01 08:06 UTC, Borda reviewed
I do not think that we shall extend EarlyStop complexity, this time seems to me as a new callback which would have only this function...

2021-03-01 08:06 UTC, Borda commented on pytorch_lightning/callbacks/early_stopping.py
> +        self.elapsed_time = 0.0
```suggestion
        self._last_time = time()
        self._elapsed_time = 0.0
```
this shall be at least protected...

2021-03-01 12:40 UTC, carmocca commented
> an optional max_time . If the elapsed time of execution (calculated from the starting time of callback creation) ever goes above max_time, then it stops

It doesn't make sense to track the time inside the EarlyStopping callback. You should instead have this timing logic in your `LightningModule` and log it as any other quantity that can be monitored by `EarlyStopping` (or in a callback as others suggested, see https://github.com/jpuigcerver/PyLaia/blob/master/laia/callbacks/training_timer.py)

2021-03-01 14:59 UTC, jlperla commented
> I do not think that we shall extend EarlyStop complexity, this time seems to me as a new callback which would have only this function...

@carmocca The problem is that these things are just as common (if not more common for many applications) than the current early stopping feature.  So having a new callback (or integrating the `max_time` thing into  the core trainer and leaving the threshold feature in a new or the existing callback) is fine but it should be formalized and unit tested.  End users should not have to get stung by complicating bugs determining when stopping should occur across multiple processes (as I was).

> It doesn't make sense to track the time inside the EarlyStopping callback. You should instead have this timing logic in your LightningModule and log it as any other quantity that can be monitored by EarlyStopping (or in a callback as others suggested, see https://github.com/jpuigcerver/PyLaia/blob/master/laia/callbacks/training_timer.py)

That doesn't work with checkpoints.  The timer on when to early stop needs to be stopped when checkpointing and restarted when the checkpoints are reloaded (in one form or another).  It has nothing to do with logging.

As I said above, I would be very happy if someone threw out this PR and did separate ones to add max_time in the trainer and did the threshold the way they want to do it, but these features are not something an end user can or should write.

2021-03-01 15:09 UTC, jlperla commented
@carmocca @Borda   The other thing I want to point out that insofar as you want people to feel comfortable doing a "fire and forget" thing on the cloud for their training, it is essential that they feel lightning has a sufficient number of robustly tested early stopping rules.  Otherwise they live in fear that something was messed up and they are spending $10/hour for no good reason on a dozen experiments that aren't stopping simply because pytorch lightning updated a version or because they coding the stopping incorreclty.

Beyond that, though, I have few opinions on how and where it is implemented in lightning.

2021-03-01 15:12 UTC, carmocca commented
> @carmocca The problem is that these things are just as common (if not more common for many applications) than the current early stopping feature

The fact that it's common does not mean it should live inside `EarlyStopping`

> leaving the threshold feature in a new or the existing callback

The threshold idea can definitely live inside `EarlyStopping` 👍 

> End users should not have to get stung by complicating bugs determining when stopping should occur across multiple processes

I'm not sure what you mean, synchronization is handled by `self.log` inside the LightningModule. `EarlyStoppping` has access to what was `log`-ged. Doesn't matter if it's time or any other number

> The timer on when to early stop needs to be stopped when checkpointing and restarted when the checkpoints are reloaded (in one form or another). It has nothing to do with logging.

You can use all the hooks available to the `LightningModule`/`Callback` to adapt the timing logic to your use case. Then those values can be `log`-ged for `ModelCheckpoint`/`EarlyStopping` to use.

2021-03-01 15:21 UTC, jlperla commented
So, sounds like we are in agreement that the threshold probably belongs in this class. If you agree, feel free to throw out what I have done here and do it properly. 

@edenlightning suggested that maybe the `max_time` should be in the core trainer, and I think that is preferred. It has a similar spirit to `max_epochs`. But I can't write that kind of code. So not sure it is worth discussing the design of having it in a callback if that would be the intention.

> You can use all the hooks available to the LightningModule/Callback to adapt the timing logic to your use case. Then those values can be log-ged for ModelCheckpoint/EarlyStopping to use.

That I don't agree with. Too buggy and scary for introductory users. This is not a thing where customization us useful,and multi GPU testing of this would be impossible for most people.

2021-03-03 18:06 UTC, tchaton requested changes
Looks good ! Please add test and make sure BC works with previous checkpoint.

2021-03-03 18:06 UTC, tchaton commented on pytorch_lightning/callbacks/early_stopping.py
> +        self.elapsed_time = callback_state["elapsed_time"]
This might break BC with previous early_stopping_state right ?

2021-03-03 18:06 UTC, tchaton commented on pytorch_lightning/callbacks/early_stopping.py
> +        if self.wait_count >= self.patience:
Could you add some tests.

2021-03-03 18:49 UTC, jlperla commented
@tchaton Thanks!  Sadly, I think I hit my level of competence and couldn't figure out how to write the tests.  If you guys have an idea for how this stuff works, then maybe throw out this PR and just add it in separately?  As @williamFalcon  and I discussed previously, I can provide the basic idea but am not tooled up for the tests (assumign that what I am suggesting makes sense, of course).  It also sounds like the max_time needs to be done in a separate change, likely in the trainer.

2021-03-17 00:18 UTC, jlperla commented
Oh had to add another one.  `divergence_threshold`.  i.e. if the monitored value is >= or <= self.divergence_threshold then it stops.

...and the latest pytorch lightning released a few hours ago broke my custom built stopping code again.  This code seems very fragile to do for users, which is yet another reason to have it formalized.

2021-04-01 17:54 UTC, jlperla commented
@tchaton   FYI: this PR is stale.  I think that the result from the discussion here is that the `max_time` is too difficult for me to implement, so it means we probably want to do this correctly in the core team.

2021-04-01 19:09 UTC, jlperla commented
clsoing.  See #6795

2021-04-01 19:09 UTC, closed without merging