[bugfix] Resolve memory leak for evaluation
PyTorchLightning/pytorch-lightning pull request #6326
Opened 2021-03-03 16:17 UTC by tchaton

## What does this PR do?

Fixes #<issue_number>

## Before submitting
- [ ] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [ ] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [ ] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [ ] Did you verify new and existing tests pass locally with your changes?
- [ ] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [ ] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
Make sure you had fun coding 🙃

2021-03-03 16:27 UTC, kaushikb11 approved these changes

2021-03-03 16:59 UTC, carmocca requested changes
Please keep the `logging_` directory name as that's done on purpose to not collide with the stdlib `logging`

2021-03-03 17:12 UTC, carmocca approved these changes

2021-03-03 17:12 UTC, carmocca commented on tests/trainer/logging_/test_eval_loop_logging_1_0.py
> +            self.batch_idx = batch_idx
Any reason to add this?

2021-03-03 17:24 UTC, tchaton commented on tests/trainer/logging_/test_eval_loop_logging_1_0.py
> +            self.batch_idx = batch_idx
removed !

2021-03-03 18:35 UTC, carmocca approved these changes

2021-03-05 07:52 UTC, akihironitta approved these changes

2021-03-05 07:52 UTC, merged