Weekly Patch Release v.1.2.9 [full merge, no squash]
PyTorchLightning/pytorch-lightning pull request #7126
Opened 2021-04-20 18:13 UTC by kaushikb11

## What does this PR do?

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [x] Check that all items from **Before submitting** are resolved
 - [x] Make sure the title is self-explanatory and the description concisely explains the PR
 - [x] Add labels and milestones (and optionally projects) to the PR so it can be classified

2021-04-20 18:16 UTC, SeanNaren approved these changes

2021-04-20 18:36 UTC, awaelchli approved these changes

2021-04-20 18:42 UTC, tchaton approved these changes
LGTM !

2021-04-20 19:03 UTC, Borda requested changes
I need to get this #6999 inside

2021-04-22 10:01 UTC, Borda commented
> I need to get this #6999 inside

it is ready just need to be merged...

2021-04-22 19:24 UTC, Borda approved these changes

2021-04-22 20:06 UTC, merged