Deprecate `LightningModule.datamodule` reference in favor of the trainer one (#6929)
PyTorchLightning/pytorch-lightning pull request #7168
Opened 2021-04-22 19:20 UTC by mesejo

## What does this PR do?

This PR attempts to deprecate datamodule and update the documentation accordingly as decided in the GitHub issue

Fixes #6929

2021-04-27 13:26 UTC, carmocca requested changes
Can you also add a test to https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/deprecated_api/test_remove_1-5.py ?

2021-04-27 13:26 UTC, carmocca commented on docs/source/common/lightning_module.rst
> +
This warning is not needed here as you updated the snippet below

2021-04-27 13:26 UTC, carmocca commented on pytorch_lightning/core/lightning.py
> +    @deprecated(deprecated_in="1.3.0", remove_in="1.5.0", target=None)
I think it's better to use `rank_zero_warn` here as there is not target.

Also for the setter

cc: @Borda

2021-05-03 08:58 UTC, awaelchli commented
added the requested test

2021-05-03 09:04 UTC, edgarriba approved these changes

2021-05-03 11:03 UTC, carmocca commented on docs/source/common/lightning_module.rst
> +
```suggestion
```

2021-05-03 11:04 UTC, carmocca commented on pytorch_lightning/core/lightning.py
> +            " Access the datamodule through the Trainer instead."
```suggestion
            " Access the datamodule through using `self.trainer.datamodule` instead."
```

2021-05-03 11:04 UTC, carmocca approved these changes

2021-05-03 11:06 UTC, carmocca commented on pytorch_lightning/core/lightning.py
> +            "The `LightningModule.datamodule` getter and setter are deprecated and will be removed in v1.5."
```suggestion
            "The `LightningModule.datamodule` property is deprecated in v1.3 and will be removed in v1.5."
```

2021-05-03 11:13 UTC, awaelchli approved these changes

2021-05-03 11:30 UTC, kaushikb11 approved these changes

2021-05-04 00:01 UTC, merged