Fix/mismatched toggle optimizer
PyTorchLightning/pytorch-lightning pull request #7563
Opened 2021-05-15 20:19 UTC by Lucklyric

## What does this PR do?

Fixes #7405

## Before submitting
- [x] Was this discussed/approved via a GitHub issue? (not for typos and docs)
- [x] Did you read the [contributor guideline](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md), **Pull Request** section?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [ ] Did you make sure to update the documentation with your changes? (if necessary)
- [ ] Did you write any new necessary tests? (not for typos and docs)
- [x] Did you verify new and existing tests pass locally with your changes?
- [x] Did you update the [CHANGELOG](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/CHANGELOG.md)? (not for typos, docs, test updates, or internal minor changes/refactorings)

## PR review
Anyone in the community is free to review the PR once the tests have passed.
Before you start reviewing make sure you have read [Review guidelines](https://github.com/PyTorchLightning/pytorch-lightning/wiki/Review-guidelines). In short, see the following bullet-list:

 - [x] Is this pull request ready for review? (if not, please submit in draft mode)
 - [ ] Check that all items from **Before submitting** are resolved
 - [ ] Make sure the title is self-explanatory and the description concisely explains the PR
 - [ ] Add labels and milestones (and optionally projects) to the PR so it can be classified

## Did you have fun?
Make sure you had fun coding 🙃

2021-05-17 17:02 UTC, carmocca requested changes
Can you resolve conflicts and add a test?

2021-05-18 12:54 UTC, SkafteNicki commented on CHANGELOG.md
> +- Changed calling of `untoggle_optimizer(opt_idx)` out of the closure function
```suggestion
- Changed calling of `untoggle_optimizer(opt_idx)` out of the closure function ([#7563](https://github.com/PyTorchLightning/pytorch-lightning/pull/7563)
```

2021-05-19 05:59 UTC, Lucklyric commented on CHANGELOG.md
> +- Changed calling of `untoggle_optimizer(opt_idx)` out of the closure function
Updated

2021-05-19 06:06 UTC, Lucklyric commented
Dear @carmocca , I just resolved the conflict. Because I only changed the place of `untoggle_optimizer`,  those codes are still covered by existing tests. The Codcov reports 0 changes on `training_loop.py`. I am actually not that sure why it shows 5% decreasing from many other files.

2021-05-19 22:10 UTC, carmocca commented
> I just resolved the conflict

Thanks!

> those codes seem to be still covered by existing tests.

Coverage is not enough. Needs a test to ensure the new behaviour is correct and to avoid future regressions

2021-05-21 11:48 UTC, tchaton commented
Dear @Lucklyric,

Mind making a test triggering the grad_fn error on master and working there.

Best,
T.C

2021-05-21 15:34 UTC, Lucklyric commented
> Dear @Lucklyric,
> 
> Mind making a test triggering the grad_fn error on master and working there.
> 
> Best,
> T.C

Will do that. Thank you!

2021-05-22 15:44 UTC, pep8speaks commented
Hello @Lucklyric! Thanks for updating this PR. 



* In the file [`tests/trainer/optimization/test_multiple_optimizers.py`](https://github.com/PyTorchLightning/pytorch-lightning/blob/2a488a16faa671fc0b92b641cbd66f40489637d0/tests/trainer/optimization/test_multiple_optimizers.py):

> [Line 172:1](https://github.com/PyTorchLightning/pytorch-lightning/blob/2a488a16faa671fc0b92b641cbd66f40489637d0/tests/trainer/optimization/test_multiple_optimizers.py#L172): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 192:58](https://github.com/PyTorchLightning/pytorch-lightning/blob/2a488a16faa671fc0b92b641cbd66f40489637d0/tests/trainer/optimization/test_multiple_optimizers.py#L192): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 207:63](https://github.com/PyTorchLightning/pytorch-lightning/blob/2a488a16faa671fc0b92b641cbd66f40489637d0/tests/trainer/optimization/test_multiple_optimizers.py#L207): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 213:67](https://github.com/PyTorchLightning/pytorch-lightning/blob/2a488a16faa671fc0b92b641cbd66f40489637d0/tests/trainer/optimization/test_multiple_optimizers.py#L213): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2021-05-22 16:16 UTC, Lucklyric commented
Dear @carmocca @tchaton , added a test that fails in master and works here. I'm not sure if this is a proper test, so please feel free to provide feedback. Thanks

2021-05-22 17:31 UTC, tchaton commented
Hey @Lucklyric @carmoccam confirm this test is failing on master.
Great job there !

2021-05-22 17:31 UTC, tchaton approved these changes
LGTM !

2021-05-22 17:34 UTC, ananthsub commented on tests/trainer/optimization/test_multiple_optimizers.py
> +def test_csutom_optimizer_step_with_multiple_optimizers(tmpdir):
```suggestion
def test_custom_optimizer_step_with_multiple_optimizers(tmpdir):
```

2021-05-22 17:39 UTC, ananthsub approved these changes

2021-05-22 17:53 UTC, carmocca approved these changes
Some nits. Thanks!

2021-05-22 17:53 UTC, carmocca commented on tests/trainer/optimization/test_multiple_optimizers.py
> +    assert all([a == b for a, b in zip(model.optimizer_step_called, [4, 2])])
```suggestion
    assert model.training_step_called == [4, 2]
    assert model.optimizer_step_called == [4, 2]
```

2021-05-22 17:53 UTC, carmocca commented on tests/trainer/optimization/test_multiple_optimizers.py
> +            using_lbfgs=False,
```suggestion
            *_,
```

2021-05-22 19:04 UTC, Lucklyric commented
> Some nits. Thanks!

Thanks for your comments, @carmocca . Updated!

2021-05-23 02:30 UTC, merged